# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'OC-Tools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MBProgressHUD'

  target 'OC-ToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OC-ToolsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
